// <auto-generated />
namespace SRS.Repositories.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class AddedJournals : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddedJournals));
        
        string IMigrationMetadata.Id
        {
            get { return "202207242241468_AddedJournals"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
