namespace SRS.Repositories.Migrations
{
    using System;
    using System.Data.Entity.Migrations;
    
    public partial class AddedFacultyReports : DbMigration
    {
        public override void Up()
        {
            DropForeignKey("dbo.CathedraReportPublications", "Publication_Id", "dbo.Publications");
            DropForeignKey("dbo.CathedraReportDissertationDefenses", "DissertationDefense_Id", "dbo.DissertationDefenses");
            DropForeignKey("dbo.CathedraReportDissertationDefense1", "DissertationDefense_Id", "dbo.DissertationDefenses");
            DropForeignKey("dbo.CathedraReportDissertationDefense2", "DissertationDefense_Id", "dbo.DissertationDefenses");
            DropForeignKey("dbo.CathedraReportThemeOfScientificWorks", "ThemeOfScientificWork_Id", "dbo.ThemeOfScientificWorks");
            DropForeignKey("dbo.CathedraReportPublication1", "Publication_Id", "dbo.Publications");
            DropForeignKey("dbo.CathedraReportPublication2", "Publication_Id", "dbo.Publications");
            DropForeignKey("dbo.CathedraReports", "User_Id", "dbo.AspNetUsers");
            RenameTable(name: "dbo.CathedraReports", newName: "DepartmentReports");
            RenameTable(name: "dbo.CathedraReportPublications", newName: "DepartmentReportPublications");
            RenameTable(name: "dbo.CathedraReportDissertationDefenses", newName: "DepartmentReportDissertationDefenses");
            RenameTable(name: "dbo.CathedraReportDissertationDefense1", newName: "DepartmentReportDissertationDefense1");
            RenameTable(name: "dbo.CathedraReportDissertationDefense2", newName: "DepartmentReportDissertationDefense2");
            RenameTable(name: "dbo.CathedraReportThemeOfScientificWorks", newName: "DepartmentReportThemeOfScientificWorks");
            RenameTable(name: "dbo.CathedraReportPublication1", newName: "DepartmentReportPublication1");
            RenameTable(name: "dbo.CathedraReportPublication2", newName: "DepartmentReportPublication2");
            RenameTable(name: "dbo.ReportCathedraReports", newName: "DepartmentReportReports");
            DropIndex("dbo.DepartmentReportPublications", new[] { "CathedraReport_Id" });
            DropIndex("dbo.DepartmentReportDissertationDefenses", new[] { "CathedraReport_Id" });
            DropIndex("dbo.DepartmentReportDissertationDefense1", new[] { "CathedraReport_Id" });
            DropIndex("dbo.DepartmentReportDissertationDefense2", new[] { "CathedraReport_Id" });
            DropIndex("dbo.DepartmentReportThemeOfScientificWorks", new[] { "CathedraReport_Id" });
            DropIndex("dbo.DepartmentReportPublication1", new[] { "CathedraReport_Id" });
            DropIndex("dbo.DepartmentReportPublication2", new[] { "CathedraReport_Id" });
            DropColumn("dbo.DepartmentReportPublications", "Publication_Id");
            DropColumn("dbo.DepartmentReportDissertationDefenses", "DissertationDefense_Id");
            DropColumn("dbo.DepartmentReportDissertationDefense1", "DissertationDefense_Id");
            DropColumn("dbo.DepartmentReportDissertationDefense2", "DissertationDefense_Id");
            DropColumn("dbo.DepartmentReportThemeOfScientificWorks", "ThemeOfScientificWork_Id");
            DropColumn("dbo.DepartmentReportPublication1", "Publication_Id");
            DropColumn("dbo.DepartmentReportPublication2", "Publication_Id");
            RenameColumn(table: "dbo.DepartmentReportPublications", name: "CathedraReport_Id", newName: "Publication_Id");
            RenameColumn(table: "dbo.CoworkersDefenses", name: "CathedraReport_Id", newName: "DepartmentReport_Id");
            RenameColumn(table: "dbo.CathedraDefenses", name: "CathedraReport_Id", newName: "DepartmentReport_Id");
            RenameColumn(table: "dbo.OtherDefenses", name: "CathedraReport_Id", newName: "DepartmentReport_Id");
            RenameColumn(table: "dbo.DepartmentReportDissertationDefenses", name: "CathedraReport_Id", newName: "DissertationDefense_Id");
            RenameColumn(table: "dbo.DepartmentReportDissertationDefense1", name: "CathedraReport_Id", newName: "DissertationDefense_Id");
            RenameColumn(table: "dbo.DepartmentReportDissertationDefense2", name: "CathedraReport_Id", newName: "DissertationDefense_Id");
            RenameColumn(table: "dbo.DepartmentReportThemeOfScientificWorks", name: "CathedraReport_Id", newName: "ThemeOfScientificWork_Id");
            RenameColumn(table: "dbo.DepartmentReportPublication1", name: "CathedraReport_Id", newName: "Publication_Id");
            RenameColumn(table: "dbo.DepartmentReportPublication2", name: "CathedraReport_Id", newName: "Publication_Id");
            RenameColumn(table: "dbo.DepartmentReportReports", name: "CathedraReport_Id", newName: "DepartmentReport_Id");
            RenameIndex(table: "dbo.CoworkersDefenses", name: "IX_CathedraReport_Id", newName: "IX_DepartmentReport_Id");
            RenameIndex(table: "dbo.CathedraDefenses", name: "IX_CathedraReport_Id", newName: "IX_DepartmentReport_Id");
            RenameIndex(table: "dbo.OtherDefenses", name: "IX_CathedraReport_Id", newName: "IX_DepartmentReport_Id");
            RenameIndex(table: "dbo.DepartmentReportReports", name: "IX_CathedraReport_Id", newName: "IX_DepartmentReport_Id");
            DropPrimaryKey("dbo.DepartmentReportPublications");
            DropPrimaryKey("dbo.DepartmentReportDissertationDefenses");
            DropPrimaryKey("dbo.DepartmentReportDissertationDefense1");
            DropPrimaryKey("dbo.DepartmentReportDissertationDefense2");
            DropPrimaryKey("dbo.DepartmentReportThemeOfScientificWorks");
            DropPrimaryKey("dbo.DepartmentReportPublication1");
            DropPrimaryKey("dbo.DepartmentReportPublication2");
            DropPrimaryKey("dbo.DepartmentReportReports");
            AddColumn("dbo.DepartmentReports", "Discriminator", c => c.String(nullable: false, maxLength: 128));
            AddColumn("dbo.DepartmentReports", "ApplicationUser_Id", c => c.String(maxLength: 128));
            AddColumn("dbo.DepartmentReportPublications", "DepartmentReport_Id", c => c.Int(nullable: false));
            AddColumn("dbo.DepartmentReportDissertationDefenses", "DepartmentReport_Id", c => c.Int(nullable: false));
            AddColumn("dbo.DepartmentReportDissertationDefense1", "DepartmentReport_Id", c => c.Int(nullable: false));
            AddColumn("dbo.DepartmentReportDissertationDefense2", "DepartmentReport_Id", c => c.Int(nullable: false));
            AddColumn("dbo.DepartmentReportThemeOfScientificWorks", "DepartmentReport_Id", c => c.Int(nullable: false));
            AddColumn("dbo.DepartmentReportPublication1", "DepartmentReport_Id", c => c.Int(nullable: false));
            AddColumn("dbo.DepartmentReportPublication2", "DepartmentReport_Id", c => c.Int(nullable: false));
            AddPrimaryKey("dbo.DepartmentReportPublications", new[] { "DepartmentReport_Id", "Publication_Id" });
            AddPrimaryKey("dbo.DepartmentReportDissertationDefenses", new[] { "DepartmentReport_Id", "DissertationDefense_Id" });
            AddPrimaryKey("dbo.DepartmentReportDissertationDefense1", new[] { "DepartmentReport_Id", "DissertationDefense_Id" });
            AddPrimaryKey("dbo.DepartmentReportDissertationDefense2", new[] { "DepartmentReport_Id", "DissertationDefense_Id" });
            AddPrimaryKey("dbo.DepartmentReportThemeOfScientificWorks", new[] { "DepartmentReport_Id", "ThemeOfScientificWork_Id" });
            AddPrimaryKey("dbo.DepartmentReportPublication1", new[] { "DepartmentReport_Id", "Publication_Id" });
            AddPrimaryKey("dbo.DepartmentReportPublication2", new[] { "DepartmentReport_Id", "Publication_Id" });
            AddPrimaryKey("dbo.DepartmentReportReports", new[] { "DepartmentReport_Id", "Report_Id" });
            CreateIndex("dbo.DepartmentReports", "ApplicationUser_Id");
            CreateIndex("dbo.DepartmentReportPublications", "DepartmentReport_Id");
            CreateIndex("dbo.DepartmentReportDissertationDefenses", "DepartmentReport_Id");
            CreateIndex("dbo.DepartmentReportDissertationDefense1", "DepartmentReport_Id");
            CreateIndex("dbo.DepartmentReportDissertationDefense2", "DepartmentReport_Id");
            CreateIndex("dbo.DepartmentReportThemeOfScientificWorks", "DepartmentReport_Id");
            CreateIndex("dbo.DepartmentReportPublication1", "DepartmentReport_Id");
            CreateIndex("dbo.DepartmentReportPublication2", "DepartmentReport_Id");
            AddForeignKey("dbo.DepartmentReportPublications", "DepartmentReport_Id", "dbo.DepartmentReports", "Id", cascadeDelete: true);
            AddForeignKey("dbo.DepartmentReportDissertationDefenses", "DepartmentReport_Id", "dbo.DepartmentReports", "Id", cascadeDelete: true);
            AddForeignKey("dbo.DepartmentReportDissertationDefense1", "DepartmentReport_Id", "dbo.DepartmentReports", "Id", cascadeDelete: true);
            AddForeignKey("dbo.DepartmentReportDissertationDefense2", "DepartmentReport_Id", "dbo.DepartmentReports", "Id", cascadeDelete: true);
            AddForeignKey("dbo.DepartmentReportThemeOfScientificWorks", "DepartmentReport_Id", "dbo.DepartmentReports", "Id", cascadeDelete: true);
            AddForeignKey("dbo.DepartmentReportPublication1", "DepartmentReport_Id", "dbo.DepartmentReports", "Id", cascadeDelete: true);
            AddForeignKey("dbo.DepartmentReportPublication2", "DepartmentReport_Id", "dbo.DepartmentReports", "Id", cascadeDelete: true);
            AddForeignKey("dbo.DepartmentReports", "ApplicationUser_Id", "dbo.AspNetUsers", "Id");
        }
        
        public override void Down()
        {
            DropForeignKey("dbo.DepartmentReports", "ApplicationUser_Id", "dbo.AspNetUsers");
            DropForeignKey("dbo.DepartmentReportPublication2", "DepartmentReport_Id", "dbo.DepartmentReports");
            DropForeignKey("dbo.DepartmentReportPublication1", "DepartmentReport_Id", "dbo.DepartmentReports");
            DropForeignKey("dbo.DepartmentReportThemeOfScientificWorks", "DepartmentReport_Id", "dbo.DepartmentReports");
            DropForeignKey("dbo.DepartmentReportDissertationDefense2", "DepartmentReport_Id", "dbo.DepartmentReports");
            DropForeignKey("dbo.DepartmentReportDissertationDefense1", "DepartmentReport_Id", "dbo.DepartmentReports");
            DropForeignKey("dbo.DepartmentReportDissertationDefenses", "DepartmentReport_Id", "dbo.DepartmentReports");
            DropForeignKey("dbo.DepartmentReportPublications", "DepartmentReport_Id", "dbo.DepartmentReports");
            DropIndex("dbo.DepartmentReportPublication2", new[] { "DepartmentReport_Id" });
            DropIndex("dbo.DepartmentReportPublication1", new[] { "DepartmentReport_Id" });
            DropIndex("dbo.DepartmentReportThemeOfScientificWorks", new[] { "DepartmentReport_Id" });
            DropIndex("dbo.DepartmentReportDissertationDefense2", new[] { "DepartmentReport_Id" });
            DropIndex("dbo.DepartmentReportDissertationDefense1", new[] { "DepartmentReport_Id" });
            DropIndex("dbo.DepartmentReportDissertationDefenses", new[] { "DepartmentReport_Id" });
            DropIndex("dbo.DepartmentReportPublications", new[] { "DepartmentReport_Id" });
            DropIndex("dbo.DepartmentReports", new[] { "ApplicationUser_Id" });
            DropPrimaryKey("dbo.DepartmentReportReports");
            DropPrimaryKey("dbo.DepartmentReportPublication2");
            DropPrimaryKey("dbo.DepartmentReportPublication1");
            DropPrimaryKey("dbo.DepartmentReportThemeOfScientificWorks");
            DropPrimaryKey("dbo.DepartmentReportDissertationDefense2");
            DropPrimaryKey("dbo.DepartmentReportDissertationDefense1");
            DropPrimaryKey("dbo.DepartmentReportDissertationDefenses");
            DropPrimaryKey("dbo.DepartmentReportPublications");
            DropColumn("dbo.DepartmentReportPublication2", "DepartmentReport_Id");
            DropColumn("dbo.DepartmentReportPublication1", "DepartmentReport_Id");
            DropColumn("dbo.DepartmentReportThemeOfScientificWorks", "DepartmentReport_Id");
            DropColumn("dbo.DepartmentReportDissertationDefense2", "DepartmentReport_Id");
            DropColumn("dbo.DepartmentReportDissertationDefense1", "DepartmentReport_Id");
            DropColumn("dbo.DepartmentReportDissertationDefenses", "DepartmentReport_Id");
            DropColumn("dbo.DepartmentReportPublications", "DepartmentReport_Id");
            DropColumn("dbo.DepartmentReports", "ApplicationUser_Id");
            DropColumn("dbo.DepartmentReports", "Discriminator");
            AddPrimaryKey("dbo.DepartmentReportReports", new[] { "Report_Id", "CathedraReport_Id" });
            AddPrimaryKey("dbo.DepartmentReportPublication2", new[] { "CathedraReport_Id", "Publication_Id" });
            AddPrimaryKey("dbo.DepartmentReportPublication1", new[] { "CathedraReport_Id", "Publication_Id" });
            AddPrimaryKey("dbo.DepartmentReportThemeOfScientificWorks", new[] { "CathedraReport_Id", "ThemeOfScientificWork_Id" });
            AddPrimaryKey("dbo.DepartmentReportDissertationDefense2", new[] { "CathedraReport_Id", "DissertationDefense_Id" });
            AddPrimaryKey("dbo.DepartmentReportDissertationDefense1", new[] { "CathedraReport_Id", "DissertationDefense_Id" });
            AddPrimaryKey("dbo.DepartmentReportDissertationDefenses", new[] { "CathedraReport_Id", "DissertationDefense_Id" });
            AddPrimaryKey("dbo.DepartmentReportPublications", new[] { "CathedraReport_Id", "Publication_Id" });
            RenameIndex(table: "dbo.DepartmentReportReports", name: "IX_DepartmentReport_Id", newName: "IX_CathedraReport_Id");
            RenameIndex(table: "dbo.OtherDefenses", name: "IX_DepartmentReport_Id", newName: "IX_CathedraReport_Id");
            RenameIndex(table: "dbo.CathedraDefenses", name: "IX_DepartmentReport_Id", newName: "IX_CathedraReport_Id");
            RenameIndex(table: "dbo.CoworkersDefenses", name: "IX_DepartmentReport_Id", newName: "IX_CathedraReport_Id");
            RenameColumn(table: "dbo.DepartmentReportReports", name: "DepartmentReport_Id", newName: "CathedraReport_Id");
            RenameColumn(table: "dbo.DepartmentReportPublication2", name: "Publication_Id", newName: "CathedraReport_Id");
            RenameColumn(table: "dbo.DepartmentReportPublication1", name: "Publication_Id", newName: "CathedraReport_Id");
            RenameColumn(table: "dbo.DepartmentReportThemeOfScientificWorks", name: "ThemeOfScientificWork_Id", newName: "CathedraReport_Id");
            RenameColumn(table: "dbo.DepartmentReportDissertationDefense2", name: "DissertationDefense_Id", newName: "CathedraReport_Id");
            RenameColumn(table: "dbo.DepartmentReportDissertationDefense1", name: "DissertationDefense_Id", newName: "CathedraReport_Id");
            RenameColumn(table: "dbo.DepartmentReportDissertationDefenses", name: "DissertationDefense_Id", newName: "CathedraReport_Id");
            RenameColumn(table: "dbo.OtherDefenses", name: "DepartmentReport_Id", newName: "CathedraReport_Id");
            RenameColumn(table: "dbo.CathedraDefenses", name: "DepartmentReport_Id", newName: "CathedraReport_Id");
            RenameColumn(table: "dbo.CoworkersDefenses", name: "DepartmentReport_Id", newName: "CathedraReport_Id");
            RenameColumn(table: "dbo.DepartmentReportPublications", name: "Publication_Id", newName: "CathedraReport_Id");
            AddColumn("dbo.DepartmentReportPublication2", "Publication_Id", c => c.Int(nullable: false));
            AddColumn("dbo.DepartmentReportPublication1", "Publication_Id", c => c.Int(nullable: false));
            AddColumn("dbo.DepartmentReportThemeOfScientificWorks", "ThemeOfScientificWork_Id", c => c.Int(nullable: false));
            AddColumn("dbo.DepartmentReportDissertationDefense2", "DissertationDefense_Id", c => c.Int(nullable: false));
            AddColumn("dbo.DepartmentReportDissertationDefense1", "DissertationDefense_Id", c => c.Int(nullable: false));
            AddColumn("dbo.DepartmentReportDissertationDefenses", "DissertationDefense_Id", c => c.Int(nullable: false));
            AddColumn("dbo.DepartmentReportPublications", "Publication_Id", c => c.Int(nullable: false));
            CreateIndex("dbo.DepartmentReportPublication2", "CathedraReport_Id");
            CreateIndex("dbo.DepartmentReportPublication1", "CathedraReport_Id");
            CreateIndex("dbo.DepartmentReportThemeOfScientificWorks", "CathedraReport_Id");
            CreateIndex("dbo.DepartmentReportDissertationDefense2", "CathedraReport_Id");
            CreateIndex("dbo.DepartmentReportDissertationDefense1", "CathedraReport_Id");
            CreateIndex("dbo.DepartmentReportDissertationDefenses", "CathedraReport_Id");
            CreateIndex("dbo.DepartmentReportPublications", "CathedraReport_Id");
            RenameTable(name: "dbo.DepartmentReportReports", newName: "ReportCathedraReports");
            RenameTable(name: "dbo.DepartmentReportPublication2", newName: "CathedraReportPublication2");
            RenameTable(name: "dbo.DepartmentReportPublication1", newName: "CathedraReportPublication1");
            RenameTable(name: "dbo.DepartmentReportThemeOfScientificWorks", newName: "CathedraReportThemeOfScientificWorks");
            RenameTable(name: "dbo.DepartmentReportDissertationDefense2", newName: "CathedraReportDissertationDefense2");
            RenameTable(name: "dbo.DepartmentReportDissertationDefense1", newName: "CathedraReportDissertationDefense1");
            RenameTable(name: "dbo.DepartmentReportDissertationDefenses", newName: "CathedraReportDissertationDefenses");
            RenameTable(name: "dbo.DepartmentReportPublications", newName: "CathedraReportPublications");
            RenameTable(name: "dbo.DepartmentReports", newName: "CathedraReports");
            AddForeignKey("dbo.CathedraReports", "User_Id", "dbo.AspNetUsers", "Id");
            AddForeignKey("dbo.CathedraReportPublication2", "Publication_Id", "dbo.Publications", "Id", cascadeDelete: true);
            AddForeignKey("dbo.CathedraReportPublication1", "Publication_Id", "dbo.Publications", "Id", cascadeDelete: true);
            AddForeignKey("dbo.CathedraReportThemeOfScientificWorks", "ThemeOfScientificWork_Id", "dbo.ThemeOfScientificWorks", "Id", cascadeDelete: true);
            AddForeignKey("dbo.CathedraReportDissertationDefense2", "DissertationDefense_Id", "dbo.DissertationDefenses", "Id", cascadeDelete: true);
            AddForeignKey("dbo.CathedraReportDissertationDefense1", "DissertationDefense_Id", "dbo.DissertationDefenses", "Id", cascadeDelete: true);
            AddForeignKey("dbo.CathedraReportDissertationDefenses", "DissertationDefense_Id", "dbo.DissertationDefenses", "Id", cascadeDelete: true);
            AddForeignKey("dbo.CathedraReportPublications", "Publication_Id", "dbo.Publications", "Id", cascadeDelete: true);
        }
    }
}
