name: Build and Publish

on:
  workflow_dispatch:
  push:
    branches:
      - features/SRS-52390

jobs:
  build:
    name: Build
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup MSBuild path
        uses: microsoft/setup-msbuild@v1.1

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1.0.5

      - name: Create Build Directory
        run: mkdir ${{github.workspace}}\_build\

      - name: Restore NuGet packages
        run: nuget restore -verbosity quiet

      - name: Build app for release
        run: msbuild SRS.sln -verbosity:minimal -t:rebuild -property:Configuration=Release /p:WebPublishMethod=FileSystem /p:DeployOnBuild=true /p:DeployDefaultTarget=WebPublish /p:PublishUrl="../_build"

      - uses: actions/upload-artifact@v3
        with:
          name: my-artifact
          path: ${{github.workspace}}\_build\

      - name: List contents of the Release directory
        run: dir ${{github.workspace}}\SRS.Testing\bin\Release\

      - name: List contents of the net48 directory
        run: dir ${{github.workspace}}\SRS.Testing\bin\Release\net48\

      - name: Download xUnit Console Runner
        run: |
          mkdir .\tools\xunit
          curl -L "https://nuget.org/api/v2/package/xunit.runner.console/2.4.1" -o xunit.zip
          Expand-Archive xunit.zip -DestinationPath .\tools\xunit
          
      - name: Run xUnit Tests
        run: |
          .\tools\xunit\tools\net472\xunit.console.exe "${{ github.workspace }}\SRS.Testing\bin\Release\net48\SRS.Testing.dll" -xml "${{ github.workspace }}\TestResults\test_results.xml"
          
      - uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: ${{github.workspace}}\TestResults\*.xml

  deploy:
    needs: build
    name: Deploy to Server using Web Deploy
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          name: my-artifact
          path: deployment

      - name: Deploy to IIS using Web Deploy
        run: |
          & "C:\Program Files (x86)\IIS\Microsoft Web Deploy V3\msdeploy.exe" --% -verb:sync -source:contentPath="C:\Users\Administrator\actions-runner\_work\lnu-reports\lnu-reports\deployment" -dest:contentPath="%SystemDrive%\inetpub\wwwroot",ComputerName="https://127.0.0.1:8172/MsDeploy.axd?site=Default Web Site",UserName="${{ secrets.SERVER_USER }}",Password="${{ secrets.SERVER_PASSWORD }}",AuthType='Basic' -allowUntrusted
